theme: jekyll-theme-architect

# Site settings
title: 产品销售                    # 你的博客网站标题
SEOTitle: 汉绣风华 # SEO 标题
description: "汉绣风华"            # 随便说点，描述一下

# Build settings
# paginate: 8                     # 一页你准备放几篇文章
